<!DOCTYPE component [
	<!ELEMENT component (name,(read|process|send|parameters)*)>
	<!ELEMENT read (input*)>
	<!ELEMENT process (#PCDATA)>
	<!ELEMENT send (output)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT input (#PCDATA)>
	<!ELEMENT output (name,host,port)>
	<!ELEMENT host (#PCDATA)>
	<!ELEMENT port (#PCDATA)>
	<!ELEMENT parameters (param*)>
	<!ELEMENT param EMPTY>
	<!ATTLIST param name CDATA #REQUIRED>
	<!ATTLIST param value CDATA #REQUIRED>
	<!ATTLIST param key CDATA "">
	<!ATTLIST param help CDATA "">
]>
<component>
	<name>EMU1</name>
	<parameters>
	</parameters>
	<read>
		<input>ROC1</input>
	</read>
</component>