<!DOCTYPE component [
	<!ELEMENT component (name,(read|process|send|parameters)*)>
	<!ELEMENT read (input*)>
	<!ELEMENT process (#PCDATA)>
	<!ELEMENT send (output)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT input (#PCDATA)>
	<!ELEMENT output (name,host,port)>
	<!ELEMENT host (#PCDATA)>
	<!ELEMENT port (#PCDATA)>
	<!ELEMENT parameters (param*)>
	<!ELEMENT param EMPTY>
	<!ATTLIST param name CDATA #REQUIRED>
	<!ATTLIST param value CDATA #REQUIRED>
	<!ATTLIST param key CDATA "">
	<!ATTLIST param help CDATA "">
]>
<component>
	<name>ROC1</name>
	<send>
		<output>
			<name>EMU1</name>
			<host>albanac</host>
			<port>11111</port>
		</output>
	</send>
	<parameters>
		<param name="debug" value="OFF"/>
		<param name="scaler setting" value="0x2456" key="x" help="hello world"/>
		<param name="readout_list" value="myreadout.so"/>
		<param name="calibration table" value="DC_wire_map.txt"/>
	</parameters>
</component>